<?php
namespace appsbd\Libs;

use appsbd\Core\AppModel;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Support\Facades\DB;


class  ApiDataResponse extends BaseResponse {
    /**
     * Its property src_by
     *
     * @var array
     */
    public array $src_by = array();
    /**
     * Its property sort_by
     *
     * @var array
     */
    public array $sort_by = array();
    /**
     * Its property is_download_csv
     *
     * @var bool
     */
    public bool $is_download_csv = false;
    /**
     * Its property csv_cols
     *
     * @var string
     */
    private string $csv_cols = '';
    /**
     * Its property is_enabled_qry_debug
     *
     * @var bool
     */
    protected $is_enabled_qry_debug=false;
    /**
     * Its property debug_data
     *
     * @var array
     */
    protected $debug_data=[];
    /**
     * Its property def_sort
     *
     * @var array
     */
    protected $def_sort=[];

    function __construct() {
        $this->data = new DataCollection();
    }

    public function enable_query_debug() {
        DB::enableQueryLog();
        $this->is_enabled_qry_debug=true;
    }

    public function setPage( int $page, int $limit ) {
        $this->data->limit = $limit;
        $this->data->page  = $page;
    }

    /**
     * The addSortData is generated by appsbd
     *
     * @param mixed $prop
     * @param string $sort_ord
     */
    public function addSortData($prop, $sort_ord = 'asc' ){
        $this->sort_by[]=['prop'=>$prop,'ord'=>$sort_ord];
    }
    /**
     * The addSortData is generated by appsbd
     *
     * @param mixed $prop
     * @param string $sort_ord
     */
    public function setDefaultSortData($prop, $sort_ord = 'asc' ) {
        $this->def_sort = [ 'prop' => $prop, 'ord' => $sort_ord ];
    }
    /**
     * The setFromRequest is generated by appsbd
     *
     * @param Request $request
     */
    public function setFromRequest( Request $request ) {
        $this->is_download_csv = ( 'Y' == $request->post( 'is_dl_csv', 'N' ) );
        if ( $this->is_download_csv ) {
            $this->csv_cols = $request->csv_cols;
        }
        $this->setPage( $request->post( 'page', 1 ), $request->post( 'limit', 20 ) );
        $this->src_by  = (array) $request->post( 'src_by', array() );
        $this->sort_by = (array) $request->post( 'sort_by', array() );
    }

    public function getLimit() {
        return $this->data->limit;
    }

    public function getPage() {
        return $this->data->page;
    }

    /**
     * The searchFromRequest is generated by appsbd
     *
     * @param Request $request
     * @param AppModel $modelClass
     * @param Class $collectionClass
     */
    public function searchFromRequest( Request $request, $modelClass, $collectionClass=JsonResource::class ,$with='',$withCount = [],$where=[],$select=null,$orWhere=[],$query=null) {
        $this->setFromRequest( $request );
        $this->getSearchData($modelClass, $collectionClass,$with,$withCount,$where,$select,$orWhere,$query);
    }
    public function getSearchData($modelClass, $collectionClass=JsonResource::class,$with='',$withCount = [],$where=[],$select=null,$orWhere=[],$query=null){
        if(empty($this->sort_by) && !empty($this->def_sort)){
            $this->sort_by[]=$this->def_sort;
        }
        $modelClass::getSearchData( $this, $collectionClass,$with,$withCount,$where,$select,$orWhere,$query);
    }

    /**
     * The set total records is generated by appsbd
     *
     * @param int $recordCounter Its record counter.
     */
    public function setRecordCount( int $recordCounter ) {
        $this->data->setRecordCount( $recordCounter );
    }

    /**
     * The setData is generated by appsbd
     *
     * @param mixed|JsonResource; $data Its row data of grid response.
     */
    public function setResource( JsonResource $data ) {

        $this->data->rowdata = $data;
    }
    public function setDebugData($key,$data){
        $this->debug_data[$key]= $data;
    }
    /**
     * The setData is generated by appsbd
     *
     * @param mixed $data
     */
    public function setData( $data ) {
        $this->data->rowdata = $data;
    }

    /**
     * The display is generated by appsbd
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function display() {
        if($this->is_enabled_qry_debug){
            $this->debug_data['queries']=DB::getQueryLog();
        }

        if(!empty($this->debug_data)){
            $response=(object)(array)$this->data;
            $response->debug=$this->debug_data;
            return response()->json( $response, 200 );
        }
        if(empty($this->data->debug) && isset($this->data->debug)){
                unset($this->data->debug);
        }
        return response()->json( $this->data, 200 );
    }
}
