<?php
namespace appsbd\Libs;

abstract class  BaseResponse {
    /**
     * Its property status
     *
     * @var bool
     */
    protected $status=false;
    /**
     * Its property httpCode
     *
     * @var string
     */
    protected $httpCode='';
    /**
     * Its property data
     *
     * @var null
     */
    public $data=null;
    /**
     * Its property msgs
     *
     * @var array[]
     */
    protected static $msgs = [
        'error'   => [

        ],
        'info'     => [

        ],
        'warning' => [

        ],
    ];

    /**
     * The getMessageString is generated by appsbd
     *
     * @param mixed $msg It is msg param.
     * @param mixed $params It is params param.
     *
     * @return array|bool|\Illuminate\Contracts\Translation\Translator|\Illuminate\Foundation\Application|object|string|null
     */
    protected static function getMessageString( $msg, $params=[] ) {
        if ( !is_string( $msg ) ) {
            return print_r( $msg, true );
        }
        foreach ($params as $placeholder => &$value) {
            $value_transate = __("values.$value");

            // If translation not found, keep original
            $value= ($value_transate === "values.$value") ? $value : $value_transate;
        }

        $msg= __($msg,$params);
      /*  if ( is_array( $params ) ) {
            $totalParams = count( $params );
            $sCount      = substr_count( $msg, '%' );
            if ( $totalParams == $sCount ) {
                return vsprintf( $msg, $params );
            }
        }*/
        return $msg;
    }

    /**
     * The addMsgArray is generated by appsbd
     *
     * @param mixed $type It is type param.
     * @param mixed $msg It is msg param.
     * @param mixed $params It is params param.
     * @param mixed $key It is key param.
     */
    protected static function addMsgArray( $type, $msg, $params=[], $key = '' ) {
        if ( $type == 'debug' && ! is_string( $msg ) ) {
            self::$msgs[ $type ][] = $msg;
        } else {
            self::$msgs[ $type ][] = self::getMessageString( $msg, $params );
        }
    }

    /**
     * The addErrorArray is generated by appsbd
     *
     * @param mixed $msg It is msg param.
     * @param mixed $params It is params param.
     * @param mixed $key It is key param.
     */
    public static function addErrorArray( $msg, $params=[], $key = '' ) {
        self::addMsgArray( 'error', $msg, $params, $key );
    }

    /**
     * The addInfoArray is generated by appsbd
     *
     * @param mixed $msg It is msg param.
     * @param mixed $params It is params param.
     * @param mixed $key It is key param.
     */
    public static function addInfoArray( $msg, $params=[], $key = '' ) {
        self::addMsgArray( 'info', $msg, $params, $key );
    }

    /**
     * The addDebugArray is generated by appsbd
     *
     * @param mixed $msg It is msg param.
     * @param mixed $params It is params param.
     * @param mixed $key It is key param.
     */
    public static function addDebugArray( $msg, $params=[], $key = '' ) {
        self::addMsgArray( 'debug', $msg, $params, $key );
    }

    /**
     * The addWarningArray is generated by appsbd
     *
     * @param mixed $msg It is msg param.
     * @param mixed $params It is params param.
     * @param mixed $key It is key param.
     */
    public static function addWarningArray( $msg, $params=[], $key = '' ) {
        self::addMsgArray( 'warning', $msg, $params=[], $key );
    }

    /**
     * The getMsgs is generated by appsbd
     *
     * @return array[]
     */
    public static function getMsgs() {
        if (!config('app.debug')) {
            if(isset(self::$msgs['debug'])){
                unset(self::$msgs['debug']);
            }
        }
        return self::$msgs;
    }

    /**
     * The setStatus is generated by appsbd
     *
     * @param mixed $status It is status param.
     * @param mixed $httpCode It is httpCode param.
     */
    public function setStatus($status,$httpCode=''){
        $this->status=$status;
        $this->httpCode=$httpCode;
    }

    /**
     * The setData is generated by appsbd
     *
     * @param mixed $data
     */
    public function setData($data){
        $this->data=$data;
    }

    /**
     * The displayWithResponse is generated by appsbd
     *
     * @param mixed $status It is status param.
     * @param mixed $data It is data param.
     * @param mixed $httpCode It is httpCode param.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function displayWithResponse($status,$data=null,$httpCode='') {
       $this->setStatus($status,$httpCode);
       $this->setData($data);
       return $this->display();
    }

    /**
     * The display is generated by appsbd
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function display() {
        if(empty($this->httpCode)){
            if($this->status){
                $this->httpCode=200;
            }else{
                $this->httpCode=422;
            }
        }
        return response()->json([
            'status'=>$this->status,
            'code'=>$this->httpCode,
            'msg'=>self::getMsgs(),
            'data'=>$this->data
        ],$this->httpCode);
    }
}
