<?php
namespace appsbd\Libs;

class  DataCollection {
    /**
     * Its property page
     *
     * @var int|mixed|string
     */
    public $page    = 0;
    /**
     * Its property limit
     *
     * @var int|mixed|string
     */
    public $limit   = 0;
    /**
     * Its property total
     *
     * @var int
     */
    public $total   = 0;
    /**
     * Its property records
     *
     * @var int
     */
    public $records = 0;
    /**
     * Its property rowdata
     *
     * @var array
     */
    public $rowdata = array();

    /**
     * The set total records is generated by appsbd
     *
     * @param int $recordCounter Its record counter.
     *
     * @return bool Its bool parameter.
     */
    public function setRecordCount( $recordCounter ) {

        $this->records = (int) $recordCounter;
        if ( $this->records > 0 ) {
            if(!empty($this->limit)){
                $this->total = ceil( $this->records / $this->limit );
            }else{
                $this->total = 1;
            }
            return true;
        }
        return false;
    }
}
