<?php
namespace appsbd\Libs;

class RoleManager {
    /**
     * The get resource is generated by appsbd
     *
     * @param any    $action_param  Its action parameter.
     * @param any    $title Its title parameter.
     * @param any    $group_title Its group title parameter.
     * @param string $tooltip_note Its tooltip note parameter.
     *
     * @return ACL_Resource
     */
    public static function get_resource( $action_param, $title, $group_title, $tooltip_note = '' ) {
        $acl_object               = new ACL_Resource();
        $acl_object->title        = $title;
        $acl_object->group_title  = $group_title;
        $acl_object->res_id       = hash( 'crc32b', $action_param );
        $acl_object->action_param = $action_param;
        $acl_object->tooltip_note = esc_attr( $tooltip_note );
        return $acl_object;
    }
}
