<template>
  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" :style="(this.color?`--vtpos-rolling-color:${this.color};`:'--vtpos-rolling-color:var(--vtpos-main-color);')+'background: none; display: block; shape-rendering: auto;'" :width="this.width" :height="this.height" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
    <circle cx="50" cy="50" fill="none" stroke-width="10" r="35" stroke-dasharray="164.93361431346415 56.97787143782138">
      <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;360 50 50" keyTimes="0;1"></animateTransform>
    </circle>
    <!-- [ldio] generated by https://loading.io/ --></svg>
</template>

<script>
export default {
name: "Rolling",
  props:{
  color:{
    type:String,
    default:''
  },
    height:{
      type:String,
      default:'20px'
    },
    width:{
      type:String,
      default:'20px'
    },
  },
  computed: {
    cssProps() {
      return {
        '--svg-height': this.height ,
        '--svg-width': this.width ,
      }
    }
  }
}
</script>

<style scoped lang="scss">
svg {
  height:var(--svg-height);
  width: var(--svg-width);
  margin: 0;
  perspective: 1rem;
  circle {
    stroke: var( --vtpos-rolling-color, #fff);
  }
}
</style>