<?php


if (! function_exists('add_action')) {
    function add_action(string $action_name, callable $func, $priority=10, $lengthOfParam=1){
        \appsbd\Libs\AppExtender::AddAction($action_name,$func,$priority,$lengthOfParam);
    }
}

if (! function_exists('add_filter')) {
    function add_filter(string $filter_name, callable $func, $priority=10, $lengthOfParam=1){
        \appsbd\Libs\AppExtender::AddFilter($filter_name,$func,$priority,$lengthOfParam);
    }
}

if (! function_exists('do_action')) {
    function do_action($action_name, ...$args){
        \appsbd\Libs\AppExtender::DoActionsParams($action_name,$args);
    }
}

if (! function_exists('apply_filters')) {
    function apply_filters($filter_name, ...$args){
        \appsbd\Libs\AppExtender::ApplyFiltersParams($filter_name,$args);
    }
}
if (! function_exists('check_access')) {
    function check_access( $action_name ) {
        //Todo:Sarwar: need to update it
        //$accepeted=['package-list','package-edit'];
        return true;//in_array($action_name,$accepeted);
    }
}
if (! function_exists('has_access')) {
    /**
     * The has access is generated by appsbd
     *
     * @param string|array $action_name It can be single action or Array of Actions
     * @param bool $isAnd If if you set true
     * then it will return true when all action has access (And condition),
     * otherwise if any one has access then it will return true (Or condition).
     */
    function has_access($action_name,$isAnd=false){
        if(!empty($action_name)){
            $isMulti=is_array($action_name);
            if($isMulti){
                $authorize=$isAnd;
                foreach ( $action_name as $action ) {
                    if(check_access($action)){
                        if(!$isAnd){
                            $authorize=true;
                            break;
                        }
                    }else{
                        if($isAnd){
                            $authorize=false;
                        }
                    }
                }
                if(!$authorize){
                    throw new \App\Exceptions\HTTPUnauthorizedException( 401, 'You do not have access to this request' );
                }
            }else {
                if(!check_access($action_name)){
                    throw new \App\Exceptions\HTTPUnauthorizedException( 401, 'You do not have access to this request' );
                }
            }

        }
    }
}
if (! function_exists('has_api_access')) {
    function has_api_access($action_name){
        if(!$action_name) { //Todo:Sarwar- need to update

            throw new \App\Exceptions\HTTPUnauthorizedException( 401, 'You do not have access to this request' );
        }
    }
}
