<?php

namespace App\Models;

use appsbd\Core\AppModel;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

/**
 * App\Models\Role
 *
 * @property int $id
 * @property string $title
 * @property string $slug
 * @property string|null $description
 * @property string|null $display_as
 * @property string $is_super  Y=Yes, N=No
 * @property string $status    A=Active, I=Inactive
 * @property int $added_by     Who added the role
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 */
class Role extends AppModel
{
    use HasFactory;
    protected $fillable = [ 'title', 'slug', 'is_super', 'status', 'added_by' ];
    /**
     * The set with query is generated by appsbd
     *
     * @param Builder $query It is query param.
     */

    public function roleAccess() {
        return $this->hasMany( RoleAccess::class, 'role_id', 'id' );
    }
    public function users() {
        return $this->hasMany(User::class,'role_id','id');
    }

    public static function getDefaultSearchProps() {
        return ['title','slug','display_as'];
    }
}

