export default [
    { id: "bagerhat", title: "Bagerhat" },
    { id: "bandarban", title: "Bandarban" },
    { id: "barguna", title: "Barguna" },
    { id: "barishal", title: "Barishal" },
    { id: "bhola", title: "Bhola" },
    { id: "bogura", title: "Bogura" },
    { id: "brahmanbaria", title: "Brahmanbaria" },
    { id: "chandpur", title: "Chandpur" },
    { id: "chapai_nawabganj", title: "Chapai Nawabganj" },
    { id: "chattogram", title: "Chattogram" },
    { id: "chuadanga", title: "Chuadanga" },
    { id: "coxs_bazar", title: "Cox’s Bazar" },
    { id: "cumilla", title: "Cumilla" },
    { id: "dhaka", title: "Dhaka" },
    { id: "dinajpur", title: "Dinajpur" },
    { id: "faridpur", title: "Faridpur" },
    { id: "feni", title: "Feni" },
    { id: "gaibandha", title: "Gaibandha" },
    { id: "gazipur", title: "Gazipur" },
    { id: "gopalganj", title: "Gopalganj" },
    { id: "habiganj", title: "Habiganj" },
    { id: "jamalpur", title: "Jamalpur" },
    { id: "jashore", title: "Jashore" },
    { id: "jhalokathi", title: "Jhalokathi" },
    { id: "jhenaidah", title: "Jhenaidah" },
    { id: "joypurhat", title: "Joypurhat" },
    { id: "khagrachhari", title: "Khagrachhari" },
    { id: "khulna", title: "Khulna" },
    { id: "kishoreganj", title: "Kishoreganj" },
    { id: "kurigram", title: "Kurigram" },
    { id: "kushtia", title: "Kushtia" },
    { id: "lakshmipur", title: "Lakshmipur" },
    { id: "lalmonirhat", title: "Lalmonirhat" },
    { id: "madaripur", title: "Madaripur" },
    { id: "magura", title: "Magura" },
    { id: "manikganj", title: "Manikganj" },
    { id: "meherpur", title: "Meherpur" },
    { id: "moulvibazar", title: "Moulvibazar" },
    { id: "munshiganj", title: "Munshiganj" },
    { id: "mymensingh", title: "Mymensingh" },
    { id: "naogaon", title: "Naogaon" },
    { id: "narail", title: "Narail" },
    { id: "narayanganj", title: "Narayanganj" },
    { id: "narsingdi", title: "Narsingdi" },
    { id: "natore", title: "Natore" },
    { id: "netrakona", title: "Netrakona" },
    { id: "nilphamari", title: "Nilphamari" },
    { id: "noakhali", title: "Noakhali" },
    { id: "pabna", title: "Pabna" },
    { id: "panchagarh", title: "Panchagarh" },
    { id: "patuakhali", title: "Patuakhali" },
    { id: "piro jpur", title: "Pirojpur" },
    { id: "rajbari", title: "Rajbari" },
    { id: "rajshahi", title: "Rajshahi" },
    { id: "rangamati", title: "Rangamati" },
    { id: "rangpur", title: "Rangpur" },
    { id: "satkhira", title: "Satkhira" },
    { id: "shariatpur", title: "Shariatpur" },
    { id: "sherpur", title: "Sherpur" },
    { id: "sirajganj", title: "Sirajganj" },
    { id: "sunamganj", title: "Sunamganj" },
    { id: "sylhet", title: "Sylhet" },
    { id: "tangail", title: "Tangail" },
    { id: "thakurgaon", title: "Thakurgaon" }
];

